# Generated by Django 2.1.5 on 2020-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20201129_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='branch',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
