# Generated by Django 3.1.2 on 2020-11-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stu_name', models.CharField(max_length=30, null='False')),
                ('password', models.CharField(max_length=20, null='False')),
                ('email', models.EmailField(max_length=30, null='False')),
                ('ph_no', models.IntegerField(primary_key='True', serialize=False)),
                ('stu_clg_name', models.CharField(max_length=50, null='False')),
                ('degree', models.CharField(max_length=10, null='False')),
            ],
        ),
    ]
