# Generated by Django 3.1.2 on 2020-11-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
